import matplotlib
matplotlib.use('Agg')

import glob, os, sys, string, numpy
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patheffects as path_effects

blank = {
    'move': 'xxxxxx',
    'color': 'brown',
}

monsters = [
    # {**blank,
    #  'name': 'orc',
    #  'move': 'xx****',
    #  'color': 'orange',
    # },
    {**blank,
     'name': 'dragon',
     'move': '*ARWAf',
     'color': 'red',
    },
    {**blank,
     'name': 'troll',
     'move': '++A++A',
     'color': 'black',
    },
    # {**blank,
    #  'name': 'ogre',
    #  'move': 'xxAxxx',
    #  'color': 'green',
    # },
    {**blank,
     'name': 'wyvern',
     'move': 'xxWxfx',
     'color': 'orange',
    },
    {**blank,
     'name': 'basilisk',
     'move': '+b++R*',
     'color': 'yellow',
    },
    {**blank,
     'name': 'fighter',
     'move': '+r*A**',
     'color': 'blue',
    },
    {**blank,
     'name': 'mage',
     'move': '+R*FB*',
     'color': 'purple',
    },
    # {**blank,
    #  'name': 'spearman',
    #  'move': '+r++++',
    #  'color': 'blue',
    # },
    # {**blank,
    #  'name': 'axeman',
    #  'move': 'xxxxxx',
    #  'color': 'green',
    # },
    {**blank,
     'name': 'healer',
     'move': 'xHxx**',
     'color': 'white',
    },
    {**blank,
     'name': 'archer',
     'move': '+R+++*',
     'color': 'green',
    },
]

actions = [
    { 'color': 'black',
      'sides': '+P+PP+',
      'count': 1, },

    { 'color': 'yellow',
      'sides': '*oP+Po',
      'count': 1, },

    { 'color': 'orange',
      'sides': 'xPxooP',
      'count': 1, },
    { 'color': 'red',
      'sides': 'o*o*SP',
      'count': 1, },

    { 'color': 'blue',
      'sides': '*x+P**',
      'count': 1, },
    { 'color': 'green',
      'sides': 'o*P+Po',
      'count': 1, },
    { 'color': 'white',
      'sides': 'xPoxoP',
      'count': 1, },
    { 'color': 'purple',
      'sides': '*oSoSP',
      'count': 1, },
]

colortests = {
    'greens': [(0,1,0), (0,0.9,0), (0,0.8,0), (0,0.6,0),
               (0,.95,0), (0,0.85,0), (0,0.7,0), (0,0.5,0)],
    'yellows': [(1,1,0), 'yellow', (0.9,0.9,0), (0.8,0.8,0),
                (.9,1,0), (1,0.9,0), (0.7,.7,0), (0.6,0.6,0)],
    'purples': ['purple', (1,0,1), (0.9,0,1), (0.8,0,1),
                (.7,0,1), (.6,0,1), (0.5,0,1), (0.4,0,1)],
    'oranges': ['orange', (1,.5,0), (1,.6,0), (1,.7,0),
                (1,.4,0), (1,.3,0), (1,0.2,0), (.8,.4,0)],
    'blues': [(0,0,1), (0.1,0.1,1), (0.2,0.2,1), (.3,.3,1),
              (0.05,0.05,1), (0.4,0.4,1), (0.15,0.15,1), (0.25,0.25,1)],
    'reds': [(1,0,0), (0.9,0,0), (0.8,0,0), (0.7,0,0),
             (.95,0,0), (0.85,0,0), (0.75,0,0), (0.65,0,0)],
}

action_descriptions = [
    {'name': 'remain aloft',
     'move': 'f',
     'color': 'red',
    },
    {'name': 'armor',
     'move': 'A',
     'color': 'black',
    },
    {'name': 'fly',
     'move': 'W',
     'color': 'orange',
    },
    {'name': 'stone',
     'move': 'b',
     'color': 'yellow',
    },
    {'name': 'move or fight any direction',
     'move': '*',
     'color': 'blue',
    },
    {'name': 'retaliate',
     'move': 'r',
     'color': 'blue',
    },
    {'name': 'move or fight diagonally',
     'move': 'x',
     'color': 'white',
    },
    {'name': 'move or fight cartesian',
     'move': '+',
     'color': 'black',
    },
    {'name': 'fireball',
     'move': 'B',
     'color': 'purple',
    },
    {'name': 'teleport',
     'move': 'F',
     'color': 'purple',
    },
    {'name': 'heal',
     'move': 'H',
     'color': 'white',
    },
    {'name': 'attack from range',
     'move': 'R',
     'color': 'green',
    },
]
